# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/asus/msm8937-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter X00H X00I X00L X00P X00R,$(TARGET_DEVICE)),)

endif
